# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: dd31acfe615a36fe35786dafcb54b4953c45fe02a694406353f59245c1cd3bf29df78989f03ea08ff2029302e71820bb6b81478c87851c5ca8e21c2d66782e8e

test:
  secret_key_base: b6c2b826eff9aeeb99d244b4c1e787982a6398370e0f6ee4d2960c893fe3f027c188c2a49aa08403ea592bf39ad08781aebec9cca0878819867f10b611a77d50

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
